#!/bin/sh

if [ "$#" -ne 1 ] && [ "$#" -ne 2 ]; then
    echo "usage: newid <tag> [--manual-id]"
    exit 1
fi

INSARGS=""

if [ "$#" -eq 2 ]; then
    if [ "$2" = '--manual-id' ]; then
        INSARGS='--manual-id'
    else
        echo "unknown argument $2"
        exit 1
    fi
fi

if ! (echo "$1" | grep -Eq  ^[a-zA-Z0-9_][a-zA-Z0-9_.-]*$) || [ "$1" = "latest" ]; then
    echo "Invalid tag name $1"
    exit 1
fi

wget -P container --no-clobber \
    http://download.adobe.com/pub/adobe/digitaleditions/ADE_2.0_Installer.exe \
    http://www.voidspace.org.uk/python/pycrypto-2.6.1/pycrypto-2.6.1.win32-py2.7.exe \
    https://raw.githubusercontent.com/apprenticeharper/DeDRM_tools/Python2/DeDRM_plugin/adobekey.py \
    https://dl.winehq.org/wine/wine-mono/7.0.0/wine-mono-7.0.0-x86.msi \
 || exit 1

docker build --tag adobe_diged_docker .
container=$(uuidgen)
docker run -p 127.0.0.1:5900:5900 --name $container adobe_diged_docker bash install.sh $INSARGS
docker commit $container "adobe_diged_docker:$1" >/dev/null
docker rm $container >/dev/null
